version: "3"
services:
  # Mongo Service
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: "on-failure"
    environment: 
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
        - 27017:27017
    volumes: 
        - ./mongo/data/:/var/lib/mongo

  cache:
    container_name: cache
    image: "redis:5.0.8-alpine"
    restart: "on-failure"
    ports: 
      - 6379:6379
    volumes:
      - ./redis/data:/var/lib/redis
  
  templates:
    image: templates:dev
    container_name: templates
    build: 
      context: "./"
    depends_on:
      - cache
      - mongodb
    links:
      - cache
      - mongodb
    ports:
      - 3001:3001
    restart: "on-failure" 
networks:
  template_networks:
    external:
      name: template_networks