version: "3"
services:
  # Mongo Service
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: "on-failure"
    environment: 
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
        - "27017:27017"
    volumes: 
        - ./mongo/data/:/var/lib/mongo

  cache:
    container_name: redis
    image: "redis:5.0.8-alpine"
    restart: "on-failure"
    expose:
      - "6379"
    ports: 
      - "6379:6379"
    volumes:
      - ./redis/data:/var/lib/redis
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'redis-cli PING'"]
      interval: 30s
      timeout: 30s
      retries: 3
