version: "3"
services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: "on-failure"
    environment: 
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
        - 27017:27017
    volumes: 
        - ./mongo/data/:/var/lib/mongo
